/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include<stdint.h>
#include<stdio.h>
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
typedef volatile unsigned int vuint32_t;
#define RCC    0x40021000
#define port_A 0x40010800
#define APB2ENR    *(volatile uint32_t*)(RCC+0x18)
#define GPIO_CRH   *(volatile uint32_t*)(port_A+0x04)
#define GPIO_ODR   *(volatile uint32_t*)(port_A+0x0C)
typedef union {
	vuint32_t all_fields;
	struct {
		vuint32_t reserved :13;
		vuint32_t p_13 :1;
	}pin;
}R_ODR_t;
volatile R_ODR_t *ptr=(volatile R_ODR_t *)(port_A+0x0C);
int main(void)
{
	APB2ENR |=(1<<2);
	GPIO_CRH &=0xFF0FFFFF;
	GPIO_CRH |=0x00200000;

	while(1)
	{
    ptr->pin.p_13=1;
    for(int i=0;i<8000;i++);
    ptr->pin.p_13=0;
    for(int i=0;i<8000;i++);
	}
}
